### ISSUE TITLE
Compile the markup

### ISSUE THREAD

**Issue by jrock2004** [sotte/presenting.vim#18]
Does this plugin compile the markdown and not show the markdown syntax? Thanks

**Comment by sotte** [comment]
I guess I should add a picture in the README.

It does not compile the markdown. It uses the syntax highlighting of vim to display everything. It looks something like this.

![presinting](https://cloud.githubusercontent.com/assets/79138/14101442/d48e3546-f594-11e5-9620-cf7ccc41199a.png)

**Comment by sotte** [comment]
I guess I can close this.
