### ISSUE TITLE
hide "--No lines in buffer--" message when presenting

### ISSUE THREAD

**Issue by jhutar** [sotte/presenting.vim#19]
When presenting, "--No lines in buffer--" message is shown. Would be nicer to have it hidden. I'm running vim with:

`vim PresentingDemo.rst -c ":set showtabline=0" -c ":set noruler" -c ":PresentingStart"`

Is it somehow possible to hide it?

**Comment by sotte** [comment]
Hey,

I just ran your command and I can't reproduce it:
![presenting-vim](https://cloud.githubusercontent.com/assets/79138/19591056/68577f08-9775-11e6-9ae0-4af1f05cacdc.png)

That being said, `:PresentingStart` could overwrite some of the options you set, not sure.

Also if I run `:PresentingStart` manually after opening the file the output looks nicer:
![presinting-vim_after](https://cloud.githubusercontent.com/assets/79138/19591191/03f09120-9776-11e6-9f45-807447551353.png)

Give me more information and maybe I can help!

**Comment by sotte** [comment]
Quick and very dirty workaround if you want to get rid of the tabline:

add `setlocal showtabline=0` after ` " some options for the buffer` in `plugins/presenting.vim`.

I guess we could make all the settings for the presentation mode configurable.

**Comment by jhutar** [comment]
Hello. Thank you very much for looking into this. This is what I see (using command in the initial comment):

![screenshot_2016-10-25_11-02-28](https://cloud.githubusercontent.com/assets/3397250/19679590/96ed62d0-9aa2-11e6-9770-0674470ab3b4.png)

and when I press "n", I get:

![screenshot_2016-10-25_11-03-54](https://cloud.githubusercontent.com/assets/3397250/19679616/bf6ee152-9aa2-11e6-81d7-b7c3474e2b3e.png)

I have moved mine `.vimrc` and `.vim/` away and still the same (after creating empty `.vim/plugin/` and placing `presenting.vim` back of-course). Mine vim is vim-enhanced-7.4.1868-1.fc24.x86_64.

**Comment by sotte** [comment]
Hey,

I also get the `--No lines in buffer--` msg. I don't know if it always was like that or if is a recent change. I also don't know how to get rid of it :(

I'm not sure if you're using the newest version (the one here on github), because you should have a progress indicator at the bottom saying, for example, `1/5`. Make sure you install the newest version!

**Comment by sotte** [comment]
https://github.com/sotte/presenting.vim/commit/dd505b657932b7d1865c60f377b76446a10d4f30 fixes the issue I think!

Please reopen if it's still a problem.
