### ISSUE TITLE
Center slide content

### ISSUE THREAD

**Issue by clobrano** [sotte/presenting.vim#22]
It would be great to have some "formatting" in the slide. Nothing fancy, just some padding on the right and on top, in order to center the content

**Comment by sotte** [comment]
Adding padding would break some of the syntax hl.

Also adding "formatting" options would open up a can of worms. There is so much to tweak the formatting...

That being said, if you have a nice implementation I'm not opposed to using it.

**Comment by designrubenz** [comment]
I just tried using presenting.vim in combination with [Goyo](https://github.com/junegunn/goyo.vim) and it seems to create the effect @clobrano asked for.

**Comment by sotte** [comment]
@designrubenz thanks for the info!

**Comment by clobrano** [comment]
@designrubenz Hi, thanks, this is quite good indeed

**Comment by sotte** [comment]
This can be closed as #26 solves it.
