### ISSUE TITLE
Indented checkboxes don't render correctly in present mode

### ISSUE THREAD

**Issue by chris542** [sotte/presenting.vim#30]
![image](https://user-images.githubusercontent.com/17423698/109084010-d2fe0180-776b-11eb-81ab-5829718807cc.png)
![image](https://user-images.githubusercontent.com/17423698/109084032-dbeed300-776b-11eb-87e7-fd8d96ee6fcb.png)

The indented checkboxes doesn't render properly

```
  elseif a:text =~? '^[*-] \[[x ]\]'
    let new_text += [substitute(substitute(a:text, '^[*-] \[ \]', '□', ''), '^[*-] \[x\]', '■', '')]
```

looks like needs to be updated, but i'm not too familiar with vim regex..

**Comment by sotte** [comment]
Thanks for reporting.
I'll check it out this weekend.

**Comment by sotte** [comment]
You're right, the regex has to be adjusted.

`'^[*-]` only matches line start (^) followed by `-` or `*`.
There should be whitespaces allowed, something like this '^\s*[*-]` (untested of course :) ).

Feel free to submit a PR!  I don't have the capacity to fix it right now.

**Comment by sotte** [comment]
@chris542 can you confirm that #33 solves this issue. Then I can close this ticket.
