### ISSUE TITLE
Syntax HL for code blocks not working

### ISSUE THREAD

**Issue by chris542** [sotte/presenting.vim#31]
![image](https://user-images.githubusercontent.com/17423698/109084289-60d9ec80-776c-11eb-9408-3940a02e2720.png)

Snippet of codes are wrappered around thick borders, but does not have any colour syntax support.
Anyway to use 'bat' if it's installed?

**Comment by sotte** [comment]
Thanks for reporting.
I'll check it out this weekend.

**Comment by sotte** [comment]
You're right, there is no syntax hl anymore. Earlier versions of presenting.vim did have this feature. I just checked out 9fb8ccc.

The bigger figlet refactoring by @PhilRunninger  must have changed the behavior and I did not c

I currently don't have the resource to fix this but feel free to contribute @chris542 

(Also `bat` is not used here.)
